-- MySQL Script generated by MySQL Workbench
-- 02/26/16 19:39:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bancomysqlotavio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancomysqlotavio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancomysqlotavio` DEFAULT CHARACTER SET utf8 ;
USE `bancomysqlotavio` ;

-- -----------------------------------------------------
-- Table `bancomysqlotavio`.`rod_jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancomysqlotavio`.`rod_jogo` ;

CREATE TABLE IF NOT EXISTS `bancomysqlotavio`.`rod_jogo` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `nom_jogo` VARCHAR(250) NOT NULL,
  `desc_jogo` VARCHAR(1000) NULL,
  `url_imagem` VARCHAR(250) NULL,
  `nom_empresa` VARCHAR(45) NULL,
  `qtd_mem_minimo` INT NULL,
  `qtd_hd_minimo` INT NULL,
  PRIMARY KEY (`id_jogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancomysqlotavio`.`rod_processador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancomysqlotavio`.`rod_processador` ;

CREATE TABLE IF NOT EXISTS `bancomysqlotavio`.`rod_processador` (
  `id_processador` INT NOT NULL AUTO_INCREMENT,
  `desc_processador` VARCHAR(250) NULL,
  `qtd_ghz` DOUBLE NULL,
  `id_equivalente` INT NULL,
  `vlr_potencia` INT NULL,
  PRIMARY KEY (`id_processador`),
  INDEX `fk_rod_processador_rod_processador_idx` (`id_equivalente` ASC),
  CONSTRAINT `fk_rod_processador_rod_processador`
    FOREIGN KEY (`id_equivalente`)
    REFERENCES `bancomysqlotavio`.`rod_processador` (`id_processador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancomysqlotavio`.`rod_placa_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancomysqlotavio`.`rod_placa_video` ;

CREATE TABLE IF NOT EXISTS `bancomysqlotavio`.`rod_placa_video` (
  `id_placa_video` INT NOT NULL,
  `desc_placa_video` VARCHAR(250) NULL,
  `qtd_clock` DOUBLE NULL,
  `vlr_potencia` INT NULL,
  `id_equivalencia` INT NULL,
  PRIMARY KEY (`id_placa_video`),
  INDEX `fk_rod_placa_video_rod_placa_video1_idx` (`id_equivalencia` ASC),
  CONSTRAINT `fk_rod_placa_video_rod_placa_video1`
    FOREIGN KEY (`id_equivalencia`)
    REFERENCES `bancomysqlotavio`.`rod_placa_video` (`id_placa_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancomysqlotavio`.`rod_jogo_placa_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancomysqlotavio`.`rod_jogo_placa_video` ;

CREATE TABLE IF NOT EXISTS `bancomysqlotavio`.`rod_jogo_placa_video` (
  `id_jogo` INT NOT NULL,
  `id_placa_video` INT NOT NULL,
  PRIMARY KEY (`id_jogo`, `id_placa_video`),
  INDEX `fk_rod_jogo_has_rod_placa_video_rod_placa_video1_idx` (`id_placa_video` ASC),
  INDEX `fk_rod_jogo_has_rod_placa_video_rod_jogo1_idx` (`id_jogo` ASC),
  CONSTRAINT `fk_rod_jogo_has_rod_placa_video_rod_jogo1`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `bancomysqlotavio`.`rod_jogo` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rod_jogo_has_rod_placa_video_rod_placa_video1`
    FOREIGN KEY (`id_placa_video`)
    REFERENCES `bancomysqlotavio`.`rod_placa_video` (`id_placa_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancomysqlotavio`.`rod_jogo_placa_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancomysqlotavio`.`rod_jogo_placa_video` ;

CREATE TABLE IF NOT EXISTS `bancomysqlotavio`.`rod_jogo_placa_video` (
  `id_jogo` INT NOT NULL,
  `id_placa_video` INT NOT NULL,
  PRIMARY KEY (`id_jogo`, `id_placa_video`),
  INDEX `fk_rod_jogo_has_rod_placa_video_rod_placa_video1_idx` (`id_placa_video` ASC),
  INDEX `fk_rod_jogo_has_rod_placa_video_rod_jogo1_idx` (`id_jogo` ASC),
  CONSTRAINT `fk_rod_jogo_has_rod_placa_video_rod_jogo1`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `bancomysqlotavio`.`rod_jogo` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rod_jogo_has_rod_placa_video_rod_placa_video1`
    FOREIGN KEY (`id_placa_video`)
    REFERENCES `bancomysqlotavio`.`rod_placa_video` (`id_placa_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
